### PR TITLE
Do not copy packages from conda-forge

### PR DESCRIPTION
**Pull request by bsipocz**
as the aim of this channel is to build version combinations that are missing there...

### CODE REVIEW

**Comment by bsipocz** [comment]
@mwcraig - I cannot make it being picked up for build on python3.4 and locally gtting all sort of errors similar to the ones I run into on conda-channel-astropy in my last few PRs. Do you have a hint how to solve this?

**Comment by mwcraig** [comment]
I think `extruder` is being built for python 2.7, 3.5 and 3.6, which is why it isn't getting picked up on python 3.4. On windows it looks like the test failure is because the skeleton recipe for pytest isn't building...looks like it has a dependency on setuptools-scm that isn't being added to the skeleton. Do you want me to try templating it?

A new version of conda-build-all was released a few days ago that *might* fix the error messages...can you please point me to a build log with the errors?

**Comment by bsipocz** [comment]
But extruder is only needed to create the recipes, isn't it? I just wonder as e.g. the astropy versions are listed for various numpies for py34, but not pytest.

I got similar errors today like this, https://travis-ci.org/bsipocz/conda-channel-astropy/jobs/258707150#L1344. I will be able to paste the full traceback once I'm back in the office tomorrow.

**Comment by mwcraig** [comment]
This can be fixed by pinning conda to 4.3.22

**Pull request closed without merging**
